# Site settings
title: "Myhro Blog"
email: ""
description: ""
baseurl: "" # the subpath of your site, e.g. /blog/
permalink: "/:year/:month/:title"
url: "https://blog.myhro.info" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
