# Site settings
title: "Myhro Blog"
author: "Tiago Ilieve"
email: ""
description: ""
baseurl: "" # the subpath of your site, e.g. /blog/
paginate: 5
paginate_path: "/page/:num"
permalink: "/:year/:month/:title"
url: "https://blog.myhro.info" # the base hostname & protocol for your site

# Build settings
gems: [jekyll-paginate]
markdown: kramdown
